const CONTACTS=[
{name:"Una",phone:"+62 831-2563-7801",wa:"6283125637801"},
{name:"Shion",phone:"+62 859-3373-8126",wa:"6285933738126"},
{name:"Gary",phone:"+65 9058 5717",wa:"6590585717"}
];
const {createClient}=window.supabase;
const sb=createClient(window.TN_SUPABASE_URL,window.TN_SUPABASE_ANON_KEY);
let seasons=[],currentId=null,adminSeasonId=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const teamCount=s=>Array.isArray(s?.teams)?s.teams.length:0;
const orderMap={"Round of 128":128,"Round of 64":64,"Round of 32":32,"Round of 16":16,"Quarterfinal":4,"Semifinal":2,"Final":1};
const roundLabel=n=>({1:"Final",2:"Semifinal",4:"Quarterfinal",8:"Round of 16",16:"Round of 32",32:"Round of 64",64:"Round of 128"}[n]||`Round of ${n*2}`);
function winner(m){if(!m||m.sa==null||m.sb==null||m.sa===m.sb)return "TBD";return Number(m.sa)>Number(m.sb)?m.a:m.b;}
function buildBracket(teams){const names=teams.map(t=>typeof t==='string'?t:t.name).filter(Boolean);if(names.length<2)return [];let size=1;while(size<names.length)size*=2;if(size>128)size=128;const slots=names.slice(0,size);while(slots.length<size)slots.push("BYE");const matches=[];let count=size/2;let prev=[];for(let i=0;i<size;i+=2){const a=slots[i]||"BYE",b=slots[i+1]||"BYE";prev.push({a,b,sa:a!=="BYE"&&b!=="BYE"?null:(a!=="BYE"?1:null),sb:a==="BYE"&&b!=="BYE"?1:null});}prev.forEach((m,i)=>matches.push({id:`r${count}-${i+1}`,round:roundLabel(count),a:m.a,b:m.b,sa:m.sa,sb:m.sb}));while(count>1){const nextCount=count/2,next=[];for(let i=0;i<count;i+=2){const a=winner(prev[i]),b=winner(prev[i+1]);const m={id:`r${nextCount}-${i/2+1}`,round:roundLabel(nextCount),a,b,sa:null,sb:null};next.push(m);matches.push(m);}prev=next;count=nextCount;}return matches;}
function recalc(matches){const rounds=[...new Set(matches.map(m=>m.round))].sort((a,b)=>(orderMap[b]||0)-(orderMap[a]||0));for(let r=0;r<rounds.length-1;r++){const cur=matches.filter(m=>m.round===rounds[r]),nxt=matches.filter(m=>m.round===rounds[r+1]);nxt.forEach((m,i)=>{m.a=cur[i*2]?winner(cur[i*2]):"TBD";m.b=cur[i*2+1]?winner(cur[i*2+1]):"TBD";if(m.a==="BYE")m.a="TBD";if(m.b==="BYE")m.b="TBD";});}}
function shuffleArray(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
async function loadSeasons(){const {data,error}=await sb.from("seasons").select("*").order("created_at",{ascending:true});if(error){$("syncState").textContent="Database error";console.error(error);return;}seasons=data||[];if(!currentId&&seasons[0])currentId=seasons[0].id;if(currentId&&!seasons.some(s=>s.id===currentId))currentId=seasons[0]?.id||null;renderPublic();$("syncState").textContent="Online · realtime";if(!$('adminPanel').classList.contains('hidden'))renderAdmin();}
function current(){return seasons.find(s=>s.id===currentId)||seasons[0];}
function renderPublic(){const s=current();if(!s){$("seasonSelect").innerHTML="";$("seasonTitle").textContent="No season yet";$("seasonTeams").textContent="0";$("seasonRegistration").textContent="0 / 0";$("bracketView").innerHTML='<div class="empty">No tournament season has been created yet.</div>';return;}$('seasonSelect').innerHTML=seasons.map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${esc(x.name)}</option>`).join('');$('seasonTitle').textContent=s.name;$('seasonStatus').textContent=s.status||'Pendaftaran';$('seasonTeams').textContent=teamCount(s);$('seasonRegistration').textContent=`${teamCount(s)} / ${s.target_teams||0}`;const pct=s.target_teams?Math.min(100,teamCount(s)/s.target_teams*100):0;$('registrationProgress').style.width=pct+'%';$('seasonDesc').textContent=s.description||'Registration and bracket updates are handled by TitikNgumpul admins.';const ms=JSON.parse(JSON.stringify(s.matches||[]));recalc(ms);renderBracket(ms);}
function renderBracket(matches){if(!matches.length){$('bracketView').innerHTML='<div class="empty">Bracket has not been created. Admin can build it from registered teams.</div>';return;}const rounds=[...new Set(matches.map(m=>m.round))].sort((a,b)=>(orderMap[b]||0)-(orderMap[a]||0));$('bracketView').innerHTML=rounds.map(r=>`<div class="round"><h4>${r}</h4>${matches.filter(m=>m.round===r).map(m=>`<div class="match-box"><div class="match-line ${m.sa!=null&&m.sb!=null&&Number(m.sa)>Number(m.sb)?'win':''}"><span>${esc(m.a)}</span><span class="score">${m.sa??'—'}</span></div><div class="match-line ${m.sa!=null&&m.sb!=null&&Number(m.sb)>Number(m.sa)?'win':''}"><span>${esc(m.b)}</span><span class="score">${m.sb??'—'}</span></div></div>`).join('')}</div>`).join('');}
function renderContacts(){$('contactsList').innerHTML=CONTACTS.map(c=>`<div class="contact-item"><b>${c.name}</b><a href="https://wa.me/${c.wa}" target="_blank" rel="noopener">${c.phone}</a></div>`).join('');}
async function login(){const email=$("loginEmail").value.trim(),password=$("loginPassword").value;const {error}=await sb.auth.signInWithPassword({email,password});$("loginMsg").textContent=error?error.message:"Login successful.";if(!error)showAdmin();}
async function logout(){await sb.auth.signOut();showLogin();}
async function showAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session){showLogin();return;}$('loginPanel').classList.add('hidden');$('adminPanel').classList.remove('hidden');renderAdmin();}
function showLogin(){$('loginPanel').classList.remove('hidden');$('adminPanel').classList.add('hidden');}
function adminSeason(){return seasons.find(s=>s.id===adminSeasonId);}
function renderAdmin(){if(!seasons.length){$('seasonList').innerHTML='<div class="empty">No seasons yet.</div>';return;}if(!adminSeasonId)adminSeasonId=currentId||seasons[0].id;const opts=seasons.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('adminSeasonSelect').innerHTML=opts;$('adminMatchSeason').innerHTML=opts;$('adminSeasonSelect').value=adminSeasonId;$('adminMatchSeason').value=adminSeasonId;$('seasonList').innerHTML=seasons.map(s=>`<div class="season-admin-item"><div><b>${esc(s.name)}</b><small>${esc(s.status||'Pendaftaran')} · ${teamCount(s)} / ${s.target_teams||0} teams</small></div><button class="btn ghost manage" data-id="${s.id}">Edit</button></div>`).join('');renderTeams();renderMatches();}
function renderTeams(){const s=adminSeason();if(!s){$('teamList').innerHTML='';return;}$('teamList').innerHTML=(s.teams||[]).map((t,i)=>`<div class="team-row"><span>#${i+1}</span><input data-team="${i}" value="${esc(t.name||t)}"><button class="danger-btn remove-team" data-i="${i}">Remove</button></div>`).join('')||'<div class="empty">No participants yet.</div>';}
function renderMatches(){const s=adminSeason();if(!s){$('matchEditor').innerHTML='';return;}$('matchEditor').innerHTML=(s.matches||[]).map((m,i)=>`<div class="match-editor"><span class="roundname">${esc(m.round)}</span><input data-i="${i}" data-k="a" value="${esc(m.a)}"><input data-i="${i}" data-k="b" value="${esc(m.b)}"><div class="score-inputs"><input data-i="${i}" data-k="sa" type="number" min="0" value="${m.sa??''}" placeholder="0"><input data-i="${i}" data-k="sb" type="number" min="0" value="${m.sb??''}" placeholder="0"></div></div>`).join('')||'<div class="empty">No bracket yet.</div>';}
async function saveSeason(s){s.updated_at=new Date().toISOString();const payload={name:s.name,status:s.status,format:s.format,description:s.description,target_teams:s.target_teams,teams:s.teams,matches:s.matches,updated_at:s.updated_at};const {data,error}=await sb.from('seasons').update(payload).eq('id',s.id).select().single();if(error)throw error;const i=seasons.findIndex(x=>x.id===s.id);if(i>=0)seasons[i]=data;currentId=s.id;adminSeasonId=s.id;renderPublic();renderAdmin();}
function openSeasonEditor(id){const s=seasons.find(x=>x.id===id);if(!s)return;$('editSeasonId').value=s.id;$('editSeasonName').value=s.name;$('editSeasonTarget').value=s.target_teams||16;$('editSeasonStatus').value=s.status||'Pendaftaran';$('editSeasonDescription').value=s.description||'';$('seasonEditorModal').classList.add('open');}
$('seasonSelect').onchange=e=>{currentId=e.target.value;renderPublic();document.querySelector('#tournament .bracket-head').scrollIntoView({behavior:'smooth'});};
$('adminOpen').onclick=async()=>{$('adminModal').classList.add('open');const {data:{session}}=await sb.auth.getSession();session?showAdmin():showLogin();};$('adminClose').onclick=()=>{$('adminModal').classList.remove('open')};$('adminModal').onclick=e=>{if(e.target===$('adminModal'))$('adminModal').classList.remove('open')};$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;
document.querySelectorAll('.at').forEach(b=>b.onclick=()=>{document.querySelectorAll('.at').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.ap').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.panel).classList.add('active');renderAdmin();});
$('seasonList').onclick=e=>{const b=e.target.closest('.manage');if(b)openSeasonEditor(b.dataset.id);};$('adminSeasonSelect').onchange=e=>{adminSeasonId=e.target.value;renderAdmin()};$('adminMatchSeason').onchange=e=>{adminSeasonId=e.target.value;renderAdmin()};
$('createSeason').onclick=async()=>{const name=$('newSeasonName').value.trim()||`TitikNgumpul Championship S${String(seasons.length+1).padStart(2,'0')}`,target=Math.max(2,Math.min(128,Number($('newSeasonSize').value)||16));const s={name,status:'Pendaftaran',format:'Single Elimination',description:'Season baru TitikNgumpul.',target_teams:target,teams:[],matches:[]};const {data,error}=await sb.from('seasons').insert(s).select().single();if(error){alert(error.message);return}seasons.push(data);currentId=data.id;adminSeasonId=data.id;$('newSeasonName').value='';renderPublic();renderAdmin();};
$('addTeam').onclick=async()=>{const s=adminSeason(),name=$('newTeamName').value.trim();if(!s||!name)return;if(teamCount(s)>=Number(s.target_teams||0)){alert('Target registration is full. Increase the target in Season Settings or remove a participant.');return}s.teams=[...(s.teams||[]),{id:crypto.randomUUID(),name}];$('newTeamName').value='';try{await saveSeason(s)}catch(e){alert(e.message)}};
$('teamList').onclick=async e=>{const b=e.target.closest('.remove-team');if(!b)return;const s=adminSeason();if(!confirm('Remove this participant?'))return;s.teams.splice(Number(b.dataset.i),1);try{await saveSeason(s)}catch(e){alert(e.message)}};$('teamList').onchange=async e=>{const i=e.target.dataset.team;if(i===undefined)return;const s=adminSeason();s.teams[Number(i)].name=e.target.value.trim()||'TBD';try{await saveSeason(s)}catch(e){alert(e.message)}};
$('generateBracket').onclick=async()=>{const s=adminSeason();if(!s||teamCount(s)<2){alert('Minimum 2 participants.');return}if(!confirm('Rebuild the bracket from the current participant list?'))return;s.matches=buildBracket(s.teams);recalc(s.matches);try{await saveSeason(s);alert('Bracket rebuilt.')}catch(e){alert(e.message)}};
$('shuffleBracket').onclick=async()=>{const s=adminSeason();if(!s||teamCount(s)<2){alert('Minimum 2 participants.');return}if(!confirm('Shuffle participants and rebuild the bracket? Existing match results will be replaced.'))return;s.teams=shuffleArray(s.teams||[]);s.matches=buildBracket(s.teams);recalc(s.matches);try{await saveSeason(s);alert('Participants shuffled and bracket updated.')}catch(e){alert(e.message)}};
$('saveBracket').onclick=async()=>{const s=adminSeason();if(!s)return;document.querySelectorAll('#matchEditor [data-i]').forEach(el=>{const m=s.matches[Number(el.dataset.i)],k=el.dataset.k;if(k==='a'||k==='b')m[k]=el.value.trim()||'TBD';else m[k]=el.value===''?null:Number(el.value)});recalc(s.matches);try{await saveSeason(s);alert('Bracket updated online.')}catch(e){alert(e.message)}};
$('resetSeason').onclick=async()=>{const s=adminSeason();if(!s||!confirm('Reset all scores?'))return;s.matches=(s.matches||[]).map(m=>({...m,sa:null,sb:null}));recalc(s.matches);try{await saveSeason(s)}catch(e){alert(e.message)}};
$('seasonEditorClose').onclick=()=>$('seasonEditorModal').classList.remove('open');$('seasonEditorModal').onclick=e=>{if(e.target===$('seasonEditorModal'))$('seasonEditorModal').classList.remove('open')};
$('saveSeasonEdit').onclick=async()=>{const s=seasons.find(x=>x.id===$('editSeasonId').value);if(!s)return;const target=Math.max(2,Math.min(128,Number($('editSeasonTarget').value)||16));s.name=$('editSeasonName').value.trim()||s.name;s.target_teams=target;s.status=$('editSeasonStatus').value;s.description=$('editSeasonDescription').value.trim();try{await saveSeason(s);$('seasonEditorModal').classList.remove('open');alert('Season updated.')}catch(e){alert(e.message)}};
$('deleteSeason').onclick=async()=>{const id=$('editSeasonId').value,s=seasons.find(x=>x.id===id);if(!s||!confirm(`Delete ${s.name}? This removes the season record and its bracket. This cannot be undone.`))return;const {error}=await sb.from('seasons').delete().eq('id',id);if(error){alert(error.message);return}seasons=seasons.filter(x=>x.id!==id);currentId=seasons[0]?.id||null;adminSeasonId=currentId||null;$('seasonEditorModal').classList.remove('open');renderPublic();renderAdmin();};
$('registerTournament').onclick=()=>{const s=current();if(s){const msg=encodeURIComponent(`Halo Una, saya ingin registrasi TitikNgumpul Tournament ${s.name}. Mohon info pendaftarannya.`);$('registerTournament').href=`https://wa.me/${CONTACTS[0].wa}?text=${msg}`}};
document.querySelectorAll('.catalog-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.catalog-tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.catalog-panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');const panel=document.querySelector(`.catalog-panel[data-panel="${tab.dataset.cat}"]`);if(panel)panel.classList.add('active');});
renderContacts();loadSeasons();sb.channel('tn-season-live-v5').on('postgres_changes',{event:'*',schema:'public',table:'seasons'},()=>loadSeasons()).subscribe();
